### ISSUE TITLE
Stripe integration exception converting payment type

### ISSUE THREAD

**Issue by emiliodavidcs** [Fermiac/woocommerce-siftscience#104]
Stripe integration is throwing an exception when converting payment type. I guess it is because wrong object property is being used.

$source->object is being used instead of $source->type:

```
private function convert_payment_type( $source ) {
		switch( $source->object ) {
			case 'card':
				return '$credit_card';
			default:
				throw new Exception( 'Unknown Stripe Source Payment Type: ' . $source->object);
		}
}
```

should be

```
private function convert_payment_type( $source ) {
		switch( $source->type ) {
			case 'card':
				return '$credit_card';
			default:
				throw new Exception( 'Unknown Stripe Source Payment Type: ' . $source->type);
		}
}
```

Could you please confirm this?

**Comment by nabsul** [comment]
Hi Emilio, thanks for reporting this! I should have time to check this out this week. I'll let you know what I find (hopefully by Sunday).

**Comment by nabsul** [comment]
Sorry I didn't get a chance to finish this off. Going to try to work on it today.

**Comment by nabsul** [comment]
@emiliodavidcs Thanks again for reporting this bug. I've been able to reproduce it. 

It looks like Strip has changed the format of their API since I wrote this plugin. The fix that you proposed would stop the error from happening, but it won't correctly fetch the credit card data (last 4 digits, etc.).

I should have a working solution and update published today.

**Comment by emiliodavidcs** [comment]
The new version does not fix the problem (the code was not changed). Did you forget that commit in the merge?

**Comment by nabsul** [comment]
Seems I botched the deployment process. I should be able to get that fixed shortly.

**Comment by nabsul** [comment]
This is really strange. It's like my fixes have just disappeared. On top of that my computer died last week so I can't even check if the changes are sitting locally on my machine.

Nevertheless, I fixed it once, so redoing it won't take much time. I'll try to do that this evening or tomorrow.

**Comment by nabsul** [comment]
Alright! I think I got it right this time.

Thanks again for the reporting this @emiliodavidcs 

PS: I've been considering taking this plugin and extending it to support other fraud solutions besides Sift Science. Before putting the effort into that, I would at least want to make sure that:

- A couple of people would benefit from that
- I might get some support in such a project (developer collaboration or at least some enthusiastic testers)

Any thoughts on this?
