### ISSUE TITLE
Enable Debug on your Account and Generate some warnings

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#120]
The goal here is to simply produce the debug errors/warnings:

1) Open `/wp/wp-config.php` and add the following lines at the end:

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```

2) Go to "WooCommerce" > "Settings" > "SiftScience"

3) Scroll down to "Batch Upload"  and first click "clear data", then click "back-fill"

![image](https://user-images.githubusercontent.com/11143071/87893905-159d7580-c9f6-11ea-8f6d-d8904af87bdb.png)

4) Open the file `wp/wp-content/debug.log`

These are the warning messages that WordPress and WooCommerce reporting and we need to fix them.

**Comment by ramico** [comment]
done successfully
