### ISSUE TITLE
Check sift.com api domain name and update if needed

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#151]
The REST API for siftscience might now be on sift.com. Let's check the documentation and update accordingly.

- File of interest is: includes/class-wc-siftscience-comm.php
- Update all the URL constants to match the latest sift.com documentation
- Also double check that the request and response JSON format has not changed

**Comment by ramico** [comment]
i'll c what i can do

**Comment by nabsul** [comment]
oops, sorry I didn't update this. It's complete.
