### ISSUE TITLE
There's is no shipping phone  

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#162]
Check for this:

* Thereb is no shipping phone

woocomerce system doesn't recognize shipping phone it, has shipping company instead which was not declared in the first place this change take good care of that
check WC_Order for reference

**Comment by ramico** [comment]
I did

**Comment by nabsul** [comment]
@ramico I double-checked and there is no shipping phone number in woocommerce:
![image](https://user-images.githubusercontent.com/11143071/88351285-8ef4db00-cd0a-11ea-98fd-1a65a46917ef.png)
