### ISSUE TITLE
Allow order to progress if "good"

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#193]
https://wordpress.org/support/topic/checkout-workflow/

**Comment by dobacco** [comment]
Hi,

Is there a way to sponsor development of this feature?

**Comment by nabsul** [comment]
Hi @dobacco. I know a developer who might be interested. Please reach out to me in a private message (Twitter for example) and I can give you details.

**Comment by nabsul** [comment]
Feature is built and in testing. New release expected next Saturday/Sunday
