### ISSUE TITLE
reconstruct the WC_SiftScience_Html class 

### ISSUE THREAD

**Issue by ramico** [Fermiac/woocommerce-siftscience#233]
actually this issue is not going to get linked right away it'll be an index 

1. review these admin methods 

- get_title
- get_text_input
- get_number_input
- get_drop_down
- get_check_box
- get_section_end 

2. create get_element method encapsulating these methods  with some logic and adjust the calls 

3. delete those methods 

4. move get_element to HTML class and readjust the calls

**Comment by nabsul** [comment]
Reopening because the previous PR is only part 1.
