### ISSUE TITLE
add JavaScript copy functionality 

### ISSUE THREAD

**Issue by ramico** [Fermiac/woocommerce-siftscience#329]
JavaScript copy functionality well be added l8r

_Originally posted by @ramico in https://github.com/Fermiac/woocommerce-siftscience/pull/328#issuecomment-694200897_

add inline script with a copy icon to  copy  innerHTML for the logs pre in debug subsection

reference : https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

**Comment by ramico** [comment]
![1200px-Copy_font_awesome svg](https://user-images.githubusercontent.com/5300122/93646756-84f00f80-fa0f-11ea-9a03-92efd8a13603.png)

**Comment by nabsul** [comment]
![image](https://user-images.githubusercontent.com/11143071/93646860-e7b7bb80-f9bb-11ea-93e5-de795f360acc.png)
