### ISSUE TITLE
Plugin leaves session open

### ISSUE THREAD

**Issue by dobacco** [Fermiac/woocommerce-siftscience#354]
With the 1.10 plugin WordPress health check complains about:

An active PHP session was detected

    A PHP session was created by a session_start() function call. This interferes with REST API and loopback requests. The session should be closed by session_write_close() before making any HTTP requests.

The REST API encountered an error

    The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

    The REST API request failed due to an error.
    Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (http_request_failed)

I have not tried with the latest code on Github.

**Comment by nabsul** [comment]
Thanks for the bug report. I don't recommend using the latest code in git. They're not as well tested as the official releases.

We'll look into this bug and release a patch when we find the fix.

**Comment by nabsul** [comment]
Is there any additional information from this error? A code line number, or a specific plugin that could be causing a conflict?

**Comment by dobacco** [comment]
That's all I was able to get from WordPress, it goes away if the sift plugin is disabled. I will test more on staging to see if I can track down the specific line.

**Comment by nabsul** [comment]
I did a little research and this seems to be an error that has started popping up with the more recent versions of wordpress. Seems fairly straight forward to fix: https://stackoverflow.com/questions/64377032/getting-an-active-php-session-was-detected-critical-warning-in-wordpress

I should be able to release a minor update to fix this over the weekend.

**Comment by nabsul** [comment]
@dobacco if you would like to try the suggested fix below, you can also make the change directly to `class-wc-siftscience-plugin.php`. 

![image](https://user-images.githubusercontent.com/11143071/114649935-3dc0b900-9c96-11eb-8ce5-abe0c04d68f2.png)

**Comment by dobacco** [comment]
Thanks, that seem to have fixed it. For 1.10 it is in `woocommerce-siftscience.php` not `class-wc-siftscience-plugin.php`
