### ISSUE TITLE
Add links to wiki documentation

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#4]
@lukassvec Can you provide the final official list of links here? Thanks!

**Comment by lukassvec** [comment]
-The banner when first installed should read:
"SiftScience Plugin activated. For setup instructions, go to [wiki link]. Your settings can be updated at: link[Woocommerce->Settings->(tab)SiftScience]."

Settings page:
-Link to setup instructions on wiki page.
-Issue reporting:
    -Check FAQ page on wiki
    -Link to bug reporting on 'issues' git page.

Link to settings page:
-In orders, use the sift column header as a link to the settings page.

**Comment by nabsul** [comment]
Closing because this is very old and most likely not relevant any more.
