### ISSUE TITLE
IP Address not sent to Sift Science

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#47]
IP Information is not being sent from Woocommerce to Sift Science

**Comment by Fidyyuan** [comment]
Got this working but not sure how to add it to the official plugin. Here's what I did:
https://github.com/Fidyyuan/woocommerce-siftscience/commit/b16fcb6cfa15d85aabda5ab88a5bc046cc714e6b

**Comment by nabsul** [comment]
That looks like the correct way to do it. To submit code directly to this repository, you would need to do a "pull request" from your repo to mine. 

No need to do that for this one-liner. If you need help doing this in the future let me know.
