### ISSUE TITLE
Updating decision (Payment OK or Looks Bad) doesn't change the order decision

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#52]
The plugin is pulling the proper decision (Payment OK or Looks Bad) from Siftscience but it's not sending it up properly.

When I check the "Payment OK" button in Wordpress/Woocommerce 
![2](https://cloud.githubusercontent.com/assets/385291/18800075/0d2bc896-81a9-11e6-9977-04de62ea78fb.PNG)
, Siftscience shows that it sent over but it doesn't update the actual Decision for the order. 
![capture](https://cloud.githubusercontent.com/assets/385291/18800054/f22f1ca0-81a8-11e6-81b2-3074d267d065.PNG)

**Comment by nabsul** [comment]
Wow. Sift Science has changed a lot since I initially implemented all of this. Before there wasn't any way to mark an order as good/bad, only a user.

This is going to require a relatively large redesign.

**Comment by nabsul** [comment]
@Fidyyuan  I'm following up with Sift Science on how to do this. The documentation isn't very clear on the difference between a user and order score/decision.

**Comment by nabsul** [comment]
Right now the good/bad in WooCommerce isn't for payment OK/bad. It is to flag the entire user as good or bad. If you flag a user as bad, it will show up as bad for all the orders that have been made by that user.

It's also important to note that the sift science score that is displayed in the plugin is per-user, and not per-order. So on siftscience.com, you'll see that the scores and good/bad label match the users, not the individual orders.

As far as I have understood, decisions on orders can only be made in the siftscience.com dashboard. That information can either be pulled or sent to the WooCommerce store, but it's basically one-way. There doesn't seem to be a way for the WooCommerce store to manipulate the order decision. 

https://siftscience.com/resources/tutorials/decisions

If this changes in the future, or I have misunderstood (I have emailed SiftScience to confirm), we can look into changing the way things work. But for now I'm going to close this issue as something we can't do anything about.
