### ISSUE TITLE
Plugin doesn't send Processed Amount to SiftScience

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#53]
Looking at the "Orders" card in Sift Science, I can see that the Total Purchased is sent over properly to SiftScience but the Total Processed is always $0.00. It doesn't send over the Status, Type or Attempts either. Is this because I requested the plugin to not to "Automatically send data" to SiftScience?

**Comment by Fidyyuan** [comment]
I currently use Stripe and Paypal. Here's some documentation on Sift working with Stripe and Paypal

https://support.siftscience.com/hc/en-us/articles/206212678-Does-Sift-work-with-Stripe-
https://support.siftscience.com/hc/en-us/articles/202978233-Does-Sift-work-with-PayPal-

**Comment by nabsul** [comment]
There are probably hundreds of different payment gateways out there, so it doesn't make sense to support them all in this plugin directly. What we do want to have in this plugin, are good hooks that people can easily use to add/change any data they want easily.

@Fidyyuan  Are you familiar with the WordPress action/filter system? If so, you'll find that I've added a few filters in `/includes/class-wc-siftscience-events.php`. You can use these to add additional data.

It might be that this plugin needs to support a few more events to make all this possible. For example, I haven't implemented an `$update_order` event in the plugin yet, and that would be useful to have.

**Comment by nabsul** [comment]
Alright. I've added the features that are needed on the plugin side to send transaction information. Now the trick is to figure out how to get the information from the payment gateway to the plugin.

@Fidyyuan Which payment gateway are you using?

**Comment by Fidyyuan** [comment]
I'm using Stripe and Paypal Standard (built-into Woocommerce) . I think Stripe would be the more important gateway to integrate since it's widely used and doesn't have very good fraud protection (unlike Paypal). I've attached my Stripe plugin here if you'd like to look at it.
[woocommerce-gateway-stripe.zip](https://github.com/Fermiac/woocommerce-siftscience/files/505279/woocommerce-gateway-stripe.zip)

**Comment by nabsul** [comment]
Perfect! I think this will be easy to figure out.

**Comment by Fidyyuan** [comment]
It seems there's a much newer version of Stripe that has rewritten some code. I've attached it here if you'd like to take a look at it. It seems that's the version that's being supported now. I'm in the middle of testing it on my own store and seeing if anything is breaking.
[woocommerce-gateway-stripe.3.0.5.zip](https://github.com/Fermiac/woocommerce-siftscience/files/507183/woocommerce-gateway-stripe.3.0.5.zip)

**Comment by Fidyyuan** [comment]
Nothing is breaking. Seems like a pretty solid plugin so please use that version instead! If you'd like some more detailed notes about it, here's their github
https://github.com/woocommerce/woocommerce-gateway-stripe

**Comment by nabsul** [comment]
@Fidyyuan I can't seem to find this "total processed" field in Sift Science. Can you point me to it?

**Comment by Fidyyuan** [comment]
When you search for a user in SiftScience, it's shown in the Order section. See the red circled part below
![screenshot 2016-10-31 at 12](https://cloud.githubusercontent.com/assets/385291/19844071/11597b34-9eff-11e6-9e8d-6f880c2a5862.jpg)

**Comment by nabsul** [comment]
Related: https://wordpress.org/support/topic/checkout-workflow/

**Comment by nabsul** [comment]
I've double checked and it appears that the plugin is correctly sending status updates to Sift Science. I've contacted their technical support to see what can be done.

**Comment by nabsul** [comment]
I got a response from the sift science team. It turns out I was sending the data in the wrong field. This should be pretty easy to fix.

**Comment by nabsul** [comment]
On the right track.

![image](https://cloud.githubusercontent.com/assets/11143071/20240159/6a509184-a8c6-11e6-9d8d-2894cd7158f3.png)

**Comment by nabsul** [comment]
Version 0.4.0 now has some basic default behaviors for orders that updates the payment and status fields in Sift Science.

It works as follows:
- When an order is created it is initially set to status "pending"
- When the order is completed, it is changed to "success"
- If the order is filed or cancelled it's set to "failed"

I'm sure this isn't going to work for every one, but it's the first step to get it working with basic "COD" payment types.

I'll next look into how to correctly plug stripe and other payment methods into this.

**Comment by Fidyyuan** [comment]
Awesome! We're getting there! I have noticed something strange though. When an order is set to Processing in Woocommerce, it sends two Pending status (2 attempts) to SiftScience. Then, when I complete the order, it sends 1 Pending and 1 Success (2 more attempts) for a total of 4 attempts.

**Comment by nabsul** [comment]
SiftScience's response to the number of attempts:

I followed up with our Product Team - it looks like Sift is functioning as intended. For that specific user, it looks like you are sending three different transactions for that user, hence the 'Pending', 'Success', then 'Failure'. While it is a bit counterintuitive, these different statuses are counted as different transactions, and so contribute to the count.
