### ISSUE TITLE
wc-siftsci-js.js is slow to load

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#59]
Just ran a test using pingdom's speed test and noticed that the Sift Science javascript (wc-siftsci-js.js) is the slowest running javascript on my site (takes about 1 second to load) compared to everything else (300ms or less). Not sure what could be done to speed it up (minify?).

**Comment by nabsul** [comment]
@Fidyyuan I don't think minify would help; it's less than 1KB. What are the other Javascript files you're comparing this to?

**Comment by Fidyyuan** [comment]
If you take a look at the Pingdom results for my site, it's the slowest loading file for some reason. 
https://tools.pingdom.com/#!/dksFkw/akibasoul.com

**Comment by nabsul** [comment]
Actually, what I just noticed is that it's not loading the .js file at all. The response is a 404 error:
https://www.akibasoul.com/wp-content/plugins/woocommerce-siftscience/tools/wc-siftsci-js.js

On my local server, the .js file loads fine. There must be a configuration difference on the servers... 

This would also affect #60
