### ISSUE TITLE
SiftScience sees $login events but not $logout events

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#62]
The Integration Health page says that it sees $login events being sent but not $logout events. Is this a bug or is no one logging out from my website?

**Comment by nabsul** [comment]
Actually, I never implemented the logout event. Now, looking at the WordPress code, it seems it's actually impossible to do so as well.

https://developer.wordpress.org/reference/functions/wp_logout/
https://siftscience.com/developers/docs/curl/events-api/reserved-events/logout

Sift Science requires the `$user_id` for this event, and WordPress doesn't provide this information in the hook.

I think a change to WordPress itself is needed to fix this.
