### ISSUE TITLE
Unable to Backfill Orders

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#66]
When I try to back-fill orders, it throws an error. 
![screenshot 2016-10-09 at 8 00 27 pm - display 1](https://cloud.githubusercontent.com/assets/385291/19330452/78be9c5c-90ac-11e6-8542-1170ae039f26.png)

I've tried clearing the data and back-fill once more but it gets stuck at the same point (after 5 orders). Interestingly enough, it sends order 14722 (which succeeds) and then order 14721 afterwards and fails. There is no order 14721 in my system so I'm not sure why it's trying to find that and send it to SiftScience.

**Comment by Fidyyuan** [comment]
Here's an error log that should make things easier!

Oct 13, 00:33:14	PHP Fatal error: Uncaught TypeError: Argument 1 passed to WC_SiftScience_Events::get_user_id() must be an instance of WC_Order, instance of WC_Order_Refund given, called in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-events.php on line 219 and defined in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-events.php:458

Stack trace:
#0 /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-events.php(219): WC_SiftScience_Events->get_user_id(Object(WC_Order_Refund))

#1 /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-api.php(66): WC_SiftScience_Events->create_order('14721')

#2 /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/api.php(23): WC_SiftScience_Api->handl in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-events.php on line 458

**Comment by Fidyyuan** [comment]
Alright, I've narrowed down how to replicate this error. 

Step 1) Locate a completed order
Step 2) Do a partial refund on the order
Step 3) Create a new order and complete it
Step 4) Clear data in SiftScience and back-fill. It will now error out.

**Comment by nabsul** [comment]
I was able to reproduce this error!

**Comment by nabsul** [comment]
The issue was that in the back-filling, the code was getting all orders. Unfortunately, a partial refund after an order is completed results in a special hidden order called an `WC_Order_Refund`. Ignoring these refund entries will avoid the error occurring.
