### ISSUE TITLE
Colors of SiftScience scores?

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#68]
I just realized that when a score has a low value, it's in bright red. When it's in the mid-range, it's orange. Should this be reversed since a low score means it's safe (so maybe green)?

**Comment by nabsul** [comment]
@Fidyyuan Do you have any suggestions for default thresholds? 
- Below what score should it be green?
- Above what score should it be red?

I'm going to make these configurable, but I'd like to have reasonable default values.

**Comment by Fidyyuan** [comment]
So far, fraudulent transactions have a score of 60+ in Sift so that's prolly good for red. 
I'd say scores under 30 should be green (legit users are rated around 8-15 in Sift for me)
