### ISSUE TITLE
Makes variation option selection area vanish

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#73]
https://wordpress.org/support/topic/makes-variation-option-selection-area-vanish/

Hello,

I’m very glad to see that there’s a Sift plugin in development, and I’d love to be a tester.

I installed the plugin on the Dobrador Shopateria and it stopped the products displaying the colour & size selections generated by the Visual Attributes plugin by QueryLoop.

Deactivating the Sift plugin returned the Visual Attributes display to the product page.

I disabled the Visual Attributes plugin, and the default drop-down option picker was available when the Sift plugin was active.

Linda

**Comment by nabsul** [comment]
Hmmm... seems to be working for me.

![image](https://cloud.githubusercontent.com/assets/11143071/20234923/869598ea-a839-11e6-9856-0d237a39561b.png)

**Comment by mugwumpr** [comment]
I just tested it again, and now the swatches and size buttons are showing (see screenshot), but this time I get the following error across the top of the page:

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/****/public_html/wp-content/themes/weaver-xtreme/header.php:24) in /home/****/public_html/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-options.php on line 49

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/****/public_html/wp-content/themes/weaver-xtreme/header.php:24) in /home/****/public_html/wp-content/plugins/fermiac-siftscience-for-woocommerce/includes/class-wc-siftscience-options.php on line 49

So, apparently the conflict is now with my theme. Gotta love wandering gremlins. Not.  :-/

![sift-science-plugin-1](https://cloud.githubusercontent.com/assets/23413873/20236204/ebde5f54-a869-11e6-94f1-73f292b40863.PNG)

**Comment by mugwumpr** [comment]
The errors on the top of the page are gone, the swatches are visible, and it's tracking data! Yay!

I did notice this error on the backend settings tab that I thought you might be interested in seeing.

![siftscience-plugin-error-2](https://cloud.githubusercontent.com/assets/23413873/20242522/009e9d4e-a8ee-11e6-9a67-a67327ba3e4e.PNG)

**Comment by mugwumpr** [comment]
Hi nabsul, here are the images I mentioned in the WP forum post:

![siftscience-plugin-3](https://cloud.githubusercontent.com/assets/23413873/20293339/b4173adc-aab2-11e6-9a87-180981971d33.PNG)
![siftscience-plugin-4](https://cloud.githubusercontent.com/assets/23413873/20293340/b418c190-aab2-11e6-9842-b47fa5bd6c5d.PNG)
![siftscience-plugin-5](https://cloud.githubusercontent.com/assets/23413873/20293341/b41e7aa4-aab2-11e6-96de-efb7650f6c16.PNG)

**Comment by nabsul** [comment]
@mugwumpr It's probably better to create new issues for slightly different types of error.
