### ISSUE TITLE
WP.org Forum request: Stripe, paypal, workflows

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#74]
From: https://wordpress.org/support/topic/checkout-workflow/

How does this do the following:

1. Integrate with Stripe and PayPal Standard where authorization only is being taken at checkout
2. In line with above if order is ‘passed’ based on score allow a workflow to progress the order and charge the payment card and process the order to completion

**Comment by SaraTaylorDemos** [comment]
Nabsul -- Looking forward to your next release for Woo integration. Thanks for all you're doing.
