### ISSUE TITLE
Check that permissions are handled correctly

### ISSUE THREAD

**Issue by nabsul** [Fermiac/woocommerce-siftscience#9]
Can only the admin see what only the admin can see?
Are there things that we should let non-admins see as well?

**Comment by lukassvec** [comment]
Everyone that has access to the backend should see the Sift.

**Comment by nabsul** [comment]
![image](https://cloud.githubusercontent.com/assets/11143071/14589696/73f48006-049d-11e6-8881-d11ae6677b52.png)
