### ISSUE TITLE
Sift Scores Not Showing

### ISSUE THREAD

**Issue by 1034media** [Fermiac/woocommerce-siftscience#93]
Integration with Sift Science works fine. I'm just having issues getting the Sift Science score to show on the orders page? The column is there but no scores are shown, same for the order page itself.

Any thoughts?

**Comment by nabsul** [comment]
Hi, Sorry I missed your report.

This is strange. Can you please check for the following:

- Are there any error messages when you save the sift science settings?
- Are there any errors in the debugging console? In Chrome, you can bring the console up with `ctrl-shift-i`, refresh the orders and see if any error messages pop up in there?

Thanks for trying the plugin out!

**Comment by nabsul** [comment]
Haven't heard from @1034media, so I'm going to close this.
